"""
synth_forensics.py
==================
Proof-of-concept pipeline for SYNTHESIS-METHOD ATTRIBUTION from error phenotypes
(Chapter 4). This is the *detect* leg of delay/detect/defend: given the error
profile of a sequenced product, infer which synthesis-method CLASS produced it.
It performs no synthesis and gives no evasion guidance.

WHAT IS REAL vs SIMULATED
-------------------------
- REAL: the pipeline (feature extraction, leakage-aware CV, calibration,
  likelihood-ratio + four-tier output, label-shuffle control). It runs unchanged
  on real UMI-consensus error tables.
- SIMULATED (for this demo only): the input error profiles, generated by a
  phenotype model whose per-method parameters are taken from the published
  primary studies below. The binding constraint for a real deployment is a
  labelled reference library from deposited product-sequence data
  (DDBJ/SRA/ENA behind Masaki, Lietard, Filges) -- NOT this simulator.

PER-METHOD PARAMETERS (sources)
-------------------------------
- Column phosphoramidite : Filges et al. 2021 (Clin Chem 67:1384) -> deletions
  ~7x substitutions, 97.2% intact; Masaki et al. 2022 (Sci Rep 12:12095) ->
  within substitutions G->A dominant (median 0.11%), capping-driven.
- Photolithographic       : Lietard et al. 2021 (NAR 49:6687) -> deletion-dominated
  (~4.65%), G->T substitution signature (~0.31%), array spatial gradient.
- Enzymatic (TdT)         : Palluk et al. 2018 (Nat Biotechnol 36:645) -> deletions
  1.3% / insertions 1.0% per step, substitutions <0.1%, aqueous (no depurination).
- OpenIDS DIY (PREDICTED) : column phosphoramidite chemistry with the capping step
  OMITTED (Kim et al. 2024). Mechanistic prediction from Masaki (G->A is
  capping-driven): capping omission SUPPRESSES the G->A signature. Separately,
  uncapped failure sequences (chains that skipped a coupling) are not terminated,
  so they re-enter the cycle and couple the NEXT base -> full-length products
  missing an internal base = ELEVATED n-1 INTERNAL DELETIONS, plus a shifted
  truncation ladder (more full-length-minus-one). This is a hypothesis to be
  tested against real OpenIDS product data, not a measurement.
"""
import numpy as np

RNG_GLOBAL = np.random.default_rng(20260715)

# ---- published per-method phenotype parameters ---------------------------
# rates are per-nucleotide fractions unless noted; substitution spectrum is the
# fraction of substitution events falling in each directed channel.
PHENOTYPES = {
    "column_phosphoramidite": dict(
        del_rate=0.00176, ins_rate=0.00020, sub_rate=0.00025,   # Filges (del ~7x sub)
        sub_spectrum=dict(GtoA=0.55, GtoT=0.15, CtoT=0.10, TtoC=0.06, AtoG=0.06, other=0.08),  # Masaki
        pos5p_slope=0.35,        # mild 5'-deletion bias (Filges)
        trunc_n1_frac=0.80, trunc_decay=0.45,   # single-base deletions predominate
        homopolymer_enrich=1.6, gc_effect=0.25,
        intra_corr=0.20,
        label="Column phosphoramidite (commercial)"),
    "photolithographic": dict(
        del_rate=0.0465, ins_rate=0.0058, sub_rate=0.0097,       # Lietard 67-mer
        sub_spectrum=dict(GtoA=0.10, GtoT=0.55, CtoT=0.08, TtoC=0.06, AtoG=0.05, other=0.16),  # G->T signature
        pos5p_slope=0.75,        # strong positional / array spatial gradient
        trunc_n1_frac=0.65, trunc_decay=0.55,
        homopolymer_enrich=1.9, gc_effect=0.40,
        intra_corr=0.45,         # spatial clustering
        label="Photolithographic (light-directed)"),
    "enzymatic_tdt": dict(
        del_rate=0.013, ins_rate=0.010, sub_rate=0.0009,         # Palluk per step
        sub_spectrum=dict(GtoA=0.18, GtoT=0.18, CtoT=0.17, TtoC=0.16, AtoG=0.16, other=0.15),  # ~flat, no dominant
        pos5p_slope=0.15,
        trunc_n1_frac=0.55, trunc_decay=0.65,   # insertion-heavy, distinctive
        homopolymer_enrich=2.2, gc_effect=0.15,
        intra_corr=0.15,
        label="Enzymatic (TdT)"),
    "openids_diy": dict(   # PREDICTED, not measured
        del_rate=0.00265, ins_rate=0.00020, sub_rate=0.00024,     # ELEVATED n-1 deletions (uncapped skips); insertion NOT elevated
        sub_spectrum=dict(GtoA=0.30, GtoT=0.20, CtoT=0.13, TtoC=0.10, AtoG=0.10, other=0.17),  # G->A partially SUPPRESSED (no capping)
        pos5p_slope=0.37,
        trunc_n1_frac=0.86, trunc_decay=0.44,   # single-base internal deletions predominate (full-length-minus-one)
        homopolymer_enrich=1.65, gc_effect=0.26,
        intra_corr=0.22,
        label="OpenIDS DIY (predicted: capping omitted)"),
}

SUB_CHANNELS = ["GtoA", "GtoT", "CtoT", "TtoC", "AtoG", "other"]

FEATURE_NAMES = (
    ["del_frac", "ins_frac", "sub_frac", "log_total_err"]      # (1) error-type spectrum
    + [f"sub_{c}" for c in SUB_CHANNELS]                        # (2) substitution spectrum
    + ["pos5p_slope"]                                          # (3) positional gradient
    + ["trunc_n1_frac", "trunc_decay"]                         # (4) truncation ladder
    + ["homopolymer_enrich", "gc_effect"]                     # (5) context conditioning
    + ["intra_corr"]                                          # (6) intra-molecule correlation
)


def simulate_batch(method, n_molecules=4000, batch_rng=None):
    """Return one error-profile feature vector for a single synthesis BATCH.

    Batch-level jitter reflects Filges et al.'s finding that batch effects can
    exceed purification effects -- so we split by batch, never by read (leakage).
    In a real deployment this function is replaced by feature extraction from a
    UMI-consensus error table; the returned vector layout is identical.
    """
    if batch_rng is None:
        batch_rng = np.random.default_rng()
    p = PHENOTYPES[method]

    # batch-level multiplicative jitter on rates (lognormal, ~24% CV)
    jit = lambda x, cv=0.24: x * np.exp(batch_rng.normal(0, cv))
    dr, ir, sr = jit(p["del_rate"]), jit(p["ins_rate"]), jit(p["sub_rate"])
    total = dr + ir + sr
    del_f, ins_f, sub_f = dr / total, ir / total, sr / total

    # substitution spectrum with Dirichlet sampling noise per batch
    base = np.array([p["sub_spectrum"][c] for c in SUB_CHANNELS])
    spec = batch_rng.dirichlet(base * 120)   # concentration -> modest batch noise

    # finite-sample estimation noise: more molecules -> tighter estimates
    est_noise = 1.0 / np.sqrt(n_molecules)
    n = lambda v, s=1.0: v + batch_rng.normal(0, est_noise * s)

    feat = (
        [n(del_f, .3), n(ins_f, .3), n(sub_f, .3), np.log10(total) + batch_rng.normal(0, .05)]
        + [max(0, n(v, .5)) for v in spec]
        + [n(jit(p["pos5p_slope"]), .5)]
        + [n(jit(p["trunc_n1_frac"]), .5), n(jit(p["trunc_decay"]), .5)]
        + [n(jit(p["homopolymer_enrich"]), .5), n(jit(p["gc_effect"]), .5)]
        + [n(jit(p["intra_corr"]), .5)]
    )
    return np.array(feat, dtype=float)


def build_dataset(methods, n_batches=12, n_molecules=4000, seed=0):
    """Simulate n_batches per method. Returns X, y (method), groups (batch id)."""
    rng = np.random.default_rng(seed)
    X, y, groups = [], [], []
    gid = 0
    for m in methods:
        for _ in range(n_batches):
            X.append(simulate_batch(m, n_molecules, np.random.default_rng(rng.integers(1e9))))
            y.append(m); groups.append(gid); gid += 1
    return np.array(X), np.array(y), np.array(groups)


# ---- likelihood-ratio -> four-tier evidentiary hierarchy (Ch4 sec 6) -----
def lr_to_tier(lr):
    if lr > 1000:  return "Tier 1 (proves-DIY-method; aspirational)"
    if lr >= 10:   return "Tier 2 (consistent-with-DIY)"
    if lr < 1:     return "Tier 3 (rules-out-commercial; realistic now)"
    return "Tier 4 (uninformative)"
